services:
  prisma-webhook:
    build: .
    container_name: prisma_webhook
    ports:
      - 7531:${PORT:-8080}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:7531/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - ./logs:/logs