name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Go application
        run: |
          go mod download
          go build -v -o prisma-webhook .

      - name: Run tests
        run: go test -v ./...
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prisma-webhook:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/prisma-webhook:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/prisma-webhook:buildcache,mode=max

      # - name: Deploy to server via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd /path/to/prisma-webhook
      #       echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #       docker-compose pull
      #       docker-compose down
      #       docker-compose up -d
      #       docker system prune -f
